#include <algorithm>
#include <iostream>
#include <sstream>

#include <grammar/yy-misc.h>
#include <semantic/function.h>
#include <semantic/compiling-space.h>
#include <output/node-base.h>
#include <report/errors.h>

#include "env.h"

static semantic::CompilingSpace globalSpace()
{
    semantic::CompilingSpace space;
    misc::position pos(0);
    std::for_each(stekin::preImported().begin()
                , stekin::preImported().end()
                , [&](std::string const& name)
                  {
                      space.sym()->imported(pos, name);
                  });
    return std::move(space);
}

int main(int argc, char* argv[])
{
    stekin::initEnv(argc, argv);
    yyparse();
    if (error::hasError()) {
        return 1;
    }
    semantic::Block global_flow(grammar::builder.buildAndClear());
    if (error::hasError()) {
        return 1;
    }
    util::sptr<output::Statement const> global_scope(global_flow.compile(globalSpace()));
    if (error::hasError()) {
        return 1;
    }
    std::stringstream os;
    os << "/* Generated by Stekinscript:Mai */" << std::endl;
    os << "(function() {" << std::endl;
    global_scope->write(os);
    os << "})();" << std::endl;
    if (error::hasError()) {
        return 1;
    }
    std::cout << os.str();
    return 0;
}
