#include <misc/version.h>

#include "global.h"

using namespace output;

void output::wrapGlobal(std::ostream& os, util::sref<Statement const> global)
{
    os << "/* Generated by Stekinscript:" + misc::version() + " */" << std::endl;
    os << "(function() {" << std::endl;
    global->write(os);
    os << "})();" << std::endl;
}
